import { createContext, useContext, useState, useEffect } from 'react';
import LanguageSalute from '@/components/language/LanguageSalute';
import CelebrationHost from '@/components/bot/CelebrationHost';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Layout
    allProjects: "All Projects",
    settings: "Settings",
    logout: "Log Out",
    online: "Online",
    search: "Search...",
    calendar: "Calendar",
    noTasksInColumn: "No tickets in this column.",
    dragHint: "drag anywhere",
    validation: "Validation",
    startupBuilder: "Startup Builder",
    integrations: "Integrations",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    newPosts: "new posts",
    newMessages: "new messages",
    liveNotifyTitle: "Team activity",
    liveNotifyFeed: "The feed was updated (post, reaction, or comment).",
    liveNotifyComment: "Someone commented on the feed.",
    liveNotifyChat: "New chat message.",
    liveNotifyBoard: "Tasks, subtasks, or ticket comments were updated.",
    liveNotifyDocs: "Notes were updated.",
    liveNotifyFiles: "Files or folders were updated.",
    liveNotifyCanvas: "The canvas was updated.",
    liveNotifyTools: "Integrations were updated.",
    liveNotifyCalendar: "The calendar was updated.",
    liveNotifyStartup: "Startup Builder was updated.",
    liveNotifyValidation: "Product ideas were updated.",
    liveNotifyGeneric: "The project was updated.",
    notificationFeedUnread: "{{count}} new posts in Feed",
    notificationChatUnread: "{{count}} new chat messages",
    notificationTeamHeading: "Team activity",
    notificationClearTeam: "Clear team notifications",
    editProfile: "Edit Profile",
    subscription: "Subscription",
    language: "Language",
    english: "English",
    german: "German",
    
    // Navigation
    dashboard: "Dashboard",
    overview: "Feeds",
    tasks: "Kanban Board",
    docs: "Notes",
    canvas: "Canvas",
    files: "Files",
    chat: "Chat",

    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Key metrics and open work at a glance.",
    dashboardTasksDone: "Completed tickets",
    dashboardTasksOpen: "Open tickets",
    dashboardTasksInProgress: "In progress",
    dashboardAssignedToMe: "Assigned to me",
    dashboardTicketOverview: "Ticket overview",
    dashboardCompletion: "Completion",
    dashboardCompletionDetail: "{{done}} of {{total}} tickets done",
    dashboardStatusTodo: "To Do",
    dashboardStatusProgress: "In Progress",
    dashboardStatusReview: "Review",
    dashboardStatusDone: "Done",
    dashboardSubtasks: "{{done}} subtasks done · {{open}} open",
    dashboardHighPriority: "{{count}} high-priority tickets still open",
    dashboardModules: "Modules",
    dashboardGoToBoard: "Open Kanban",
    dashboardOpenTickets: "Open tickets",
    dashboardViewAll: "View all",
    dashboardNoOpenTasks: "No open tickets — great job!",
    dashboardRecentlyDone: "Recently completed",
    dashboardNoDoneYet: "No completed tickets yet.",
    dashboardUntitled: "Untitled",
    dashboardUpcomingEvents: "Upcoming events",

    // Common UI
    filesTitle: "Files",
    filesSubtitle: "Manage files and documents",
    uploadFiles: "Upload files",
    uploadingCount: "Uploading… ({{count}})",
    dropFilesHere: "Drop files here",
    tapToUpload: "Tap to upload",
    newFolder: "New folder",
    folderName: "Folder name",
    createFolder: "Create folder",
    deleteAllFiles: "Delete all files?",
    backToOverview: "Back to overview",
    previewUnavailable: "Preview not available",
    downloadFile: "Download",
    fileMissing: "File missing",
    shareLink: "Share link",
    copied: "Copied",
    fullscreen: "Fullscreen",
    loadingShort: "Loading…",
    projectFeed: "Project Feed",
    feedSubtitle: "Updates, announcements and team discussions.",
    feedLoading: "Loading feed…",
    feedLoadFailed: "Could not load the feed",
    retry: "Reload",
    whatsNew: "What's new?",
    photosCount: "Photos ({{used}}/{{max}})",
    uploading: "Uploading…",
    postSubmit: "Post update",
    posting: "Posting…",
    postFailed: "Post could not be saved.",
    noPostsYet: "No posts yet",
    createFirstPost: "Write the first one!",
    teamMember: "Team member",
    react: "React",
    commentsCount: "{{count}} comments",
    writeComment: "Write a comment…",
    noCommentsYet: "No comments yet",
    delete: "Delete",
    pinPost: "Pin post",
    unpinPost: "Unpin post",
    pinnedPost: "Pinned",
    pinFailed: "Pin could not be saved.",
    noProjectAccess: "No access to this project",
    backToProjects: "Back to projects",
    tryAgain: "Try again",
    
    // ProjectsList
    myProjects: "My Projects",
    selectProject: "Select a project or create a new one to get started",
    createProject: "Create Project",
    newProject: "New Project",
    projectName: "Project Name",
    projectNamePlaceholder: "e.g. My Project",
    description: "Description (optional)",
    descriptionPlaceholder: "What is this project about...",
    createAndOpen: "Create and Open",
    noProjects: "No Projects",
    noProjectsDesc: "Create your first project to get started",
    createFirstProject: "Create First Project",
    noDescription: "No description",
    members: "members",
    deleteProject: "Delete Project",
    deleteProjectConfirm: "Really delete this project?",

    // ProjectsList (extended)
    ideaHubTitle: "Ideas Hub",
    ideaHubSubtitle: "Collect ideas — start a full project when you're ready.",
    ideaHubAdd: "New idea",
    ideaHubAddFirst: "Add first idea",
    ideaHubBack: "Back to projects",
    ideaHubEmptyTitle: "No ideas yet",
    ideaHubEmptyDesc: "Capture product ideas, features, or side projects here. Convert any idea into a project with one click.",
    ideaHubOpenSection: "Open ideas",
    ideaHubConvertedSection: "Started as project",
    ideaHubFieldTitle: "Title",
    ideaHubFieldTitlePlaceholder: "e.g. Mood tracker app for teams",
    ideaHubFieldDesc: "Notes (optional)",
    ideaHubFieldDescPlaceholder: "What problem does it solve? Who is it for?",
    ideaHubEdit: "Edit idea",
    ideaHubStartProject: "Start as project",
    ideaHubOpenProject: "Open project",
    ideaHubStatusOpen: "Open",
    ideaHubStatusConverted: "Project",
    ideaHubNoDescription: "No notes",
    ideaHubTitleRequired: "Please enter a title.",
    ideaHubSaveFailed: "Could not save idea",
    ideaHubDeleteFailed: "Could not delete idea",
    ideaHubConvertFailed: "Could not create project",
    ideaHubProjectCreated: "Project created",
    ideaHubLoading: "Loading ideas…",
    ideaHubLocalOnlyHint: "Ideas are stored only in this browser. Sign in with Google to sync across devices.",
    decideWhatToDo: "What would you like to do?",
    chooseOptionToStart: "Choose an option to start",
    toMyProjects: "To my projects",
    newShort: "New",
    projectCreateFailedTitle: "Project could not be created",
    projectCreateFailedDesc: "Please sign in with Google for cloud storage or check the error.",
    enterProjectName: "Please enter a project name",
    retry: "Try again",
    createFirstProjectCta: "Create first project",
    hiddenAllTitle: "All projects are hidden",
    hiddenAllDesc: "Show hidden projects again or create a new one.",
    showHidden: "Show hidden",
    editProject: "Edit project",
    name: "Name",
    coverImage: "Cover image",
    membersMax: "Members (max {{max}})",
    commaSeparated: "Comma-separated.",
    save: "Save",
    saving: "Saving…",
    viewToggleList: "List",
    viewToggleGrid: "Grid",
    reset: "Reset",
    statsLoading: "Stats…",
    workspace: "Workspace",
    dragProjectsHere: "Drag projects here",
    dropProjectsHere: "Drop projects here to pin them to your workspace.",
    favorites: "Favorites",
    projects: "Projects",
    projectsMine: "My projects",
    projectsSharedWithMe: "Shared with me",
    projectsSharedHint: "You were invited as a member. Editing project settings is only available to the owner.",
    noOwnProjectsYet: "You don’t have your own projects yet — create one with “New” above.",
    totalTime: "Total time",
    last: "Last",
    notTrackedYet: "Not tracked yet",
    feeds: "Feeds",
    activeModules: "Active modules",
    removeFromWorkspace: "Remove from workspace",
    timerSyncedHint:
      "Tracked time is saved when you stop the timer or leave the tab. Open the project list on another device and refresh to see the same totals (Google sign-in required).",
    projectDoneBadge: "Done",
    markProjectDone: "Mark project as done",
    markProjectActive: "Mark project as active",
    projectMarkDoneLabel: "Project completed",
    projectMarkDoneHint: "Done projects stay visible; you can reopen them anytime.",
    
    // Tasks
    sprintBoard: "Sprint Board",
    addTask: "Add Task",
    clearAll: "Clear All",
    createNewTask: "Create New Task",
    editTask: "Edit Task",
    taskTitle: "Task Title",
    priority: "Priority",
    dependencies: "Dependencies",
    mentionAll: "Everyone",
    calendarLoading: "Loading events…",
    contactCareTitle: "Nurture your contacts",
    contactCareSettingDesc: "Get reminded to reach out to three people — to keep relationships warm and make new ones. This is personal and applies to all your projects.",
    contactCareEnable: "Remind me",
    contactCareInterval: "How often?",
    contactCareEvery: "Every {n} day(s)",
    contactCarePrompt: "Reach out to three people today. Who did you write to?",
    contactCareName: "Name",
    contactCareHint: "The card keeps pulsing until all three names are in.",
    contactCareReady: "Great — save it and the reminder rests.",
    contactCareDone: "Done, three contacts",
    contactCareThanks: "Saved. Well done.",
    contactCareAllGood: "All caught up.",
    contactCareNext: "Next reminder: {date}.",
    contactCareLast: "Last time",
    newEvent: "Event",
    eventTitle: "Title",
    eventDescription: "Description (optional)",
    eventStart: "Start",
    eventEnd: "End",
    eventColor: "Colour",
    joinVideoInApp: "Join the video meeting in ORBYLOX",
    noEventsThisMonth: "No events this month.",
    tapDayToAdd: "Tap a day to add one.",
    allDay: "All day",
    chatPlaceholder: "Message… (@ to mention)",
    mentionedYou: "mentioned you",
    openChat: "Open chat",
    waitsFor: "Waits for",
    blocksTheseTasks: "Blocks these tickets",
    addDependency: "Add a ticket it waits for",
    searchTicket: "Search ticket…",
    noDependencies: "Waits for nothing — can be worked on right away.",
    blockedBadge: "Blocked",
    blockedByCount: "Blocked by {n} open ticket(s)",
    cannotMoveToDone: "This ticket waits for: {list}",
    removeDependency: "Remove dependency",
    noTicketsFound: "No matching ticket",
    wouldLoop: "Not possible — that would create a loop.",
    assignedMailSent: "{name} was notified by email.",
    assignTo: "Assign to...",
    unassigned: "Unassigned",
    available: "Available",
    person: "person",
    people: "people",
    goToSettings: "Go to Settings to add team",
    updateTask: "Update Task",
    createTask: "Create Task",
    deleteAllTasks: "Delete all tasks?",
    low: "Low",
    medium: "Medium",
    high: "High",
    todo: "To Do",
    inProgress: "In Progress",
    review: "Review",
    done: "Done",
    
    // Settings
    projectSettings: "Project Settings",
    managePreferences: "Manage your project preferences and team.",
    generalInfo: "General Information",
    updateDetails: "Update your project details.",
    teamMembers: "Team Members",
    inviteFriends: "Invite friends to collaborate on the project. They will receive an email invitation.",
    inviteToProject: "Invite to Project",
    howToInvite: "How to invite friends?",
    inviteStep1: "1. Click 'Invite to Project' button above",
    inviteStep2: "2. Enter your friend's email",
    inviteStep3: "3. We will send them an invitation automatically",
    inviteStep4: "4. After logging in, they will see all changes in real-time!",
    features: "Features",
    enableDisableFeatures: "Enable or disable features.",
    textToTicket: "Text to Ticket",
    textToTicketDesc: "Highlight text to automatically create tickets",
    backupRestore: "Backup & Restore",
    createBackups: "Create backups and restore your project.",
    
    // Canvas
    clearAllItems: "Delete all items?",
    typeHere: "Type here...",
    writeHere: "Write here...",
    
    // Chat
    teamChat: "Team Chat",
    typeMessage: "Type a message...",
    send: "Send",
    deleteAllMessages: "Delete all messages?",
    team: "Team",
    deleteChatHistory: "Delete chat history?",
    startVideoCall: "Start Video Call",
    
    // Docs
    documents: "Documents",
    newDocument: "New Document",
    deleteAllDocs: "Delete all documents?",
    untitledDocument: "Untitled Document",
    noDocSelected: "No document selected",
    selectOrCreate: "Select a document from the list or create a new one",
    dragDropFiles: "Drag & drop files here",
    orClick: "or click to browse",
    uploadedFiles: "Uploaded Files",
    
    // FileHub
    myFiles: "My Files",
    uploadFile: "Upload File",
    deleteAllFiles: "Delete all files?",
    folders: "Folders",
    recentFiles: "Recent Files",
    download: "Download",
    delete: "Delete",
    
    // Landing
    forStudentsAndStartups: "For Students & Young Startups",
    planProjects: "Plan projects.",
    implementIdeas: "Implement ideas.",
    landingSubtitle: "ORBYLOX is your all-in-one project management tool with integrated idea validation. Perfect for teams who work structured and want to realize their visions.",
    readyIn10Min: "Ready in 5 min",
    gdprCompliant: "GDPR compliant",
    studentFriendly: "Student friendly",
    startFree: "Start for free",
    login: "Login",
    builtForTeamsLikeYou: "Built for teams like you",
    students: "Students",
    studentsDesc: "Who want to start their first project or startup",
    freshStartups: "Fresh Startups",
    freshStartupsDesc: "Teams of 1-5 people with big ideas",
    friendGroups: "Friend Groups",
    friendGroupsDesc: "Who want to start a startup together",
    whatMakesSpecial: "What makes ORBYLOX special",
    simpleStartGrowTogether: "Simple start, grow together.",
    min10Onboarding: "5 Minute Onboarding",
    min10OnboardingDesc: "No feature overload. Start immediately without complicated setup.",
    minimalistInterface: "Minimalist Interface",
    minimalistInterfaceDesc: "Clear focus on essentials. Easy to understand, easy to use.",
    fromIdeaToPlan: "From Idea to Plan",
    fromIdeaToPlanDesc: "Built for beginners: Validate your idea and create concrete first steps.",
    gdprCompliantTitle: "GDPR Compliant",
    gdprCompliantDesc: "Your data stays in Germany. Privacy is not a compromise for us.",
    studentFriendlyTitle: "Student Friendly",
    studentFriendlyDescLong: "Fair prices for teams just starting out. No enterprise pricing.",
    ideaValidationIntegrated: "Idea Validation Integrated",
    ideaValidationIntegratedDesc: "Test your business idea with methods from Lean Startup, Design Thinking & more.",
    everythingYouNeed: "Everything you need",
    focusedToolsNoOverload: "Focused tools without overload",
    kanbanBoard: "Kanban Board",
    kanbanBoardDesc: "Organize your tasks visually. Drag & drop, priorities, assignment – all included.",
    dragDropInterface: "Drag & Drop Interface",
    prioritiesDeadlines: "Priorities & Deadlines",
    teamAssignment: "Team Assignment",
    ideaValidation: "Idea Validation",
    ideaValidationDesc: "Test your business idea with proven methods like Lean Startup or Design Thinking.",
    validationMethods: "5 Validation Methods",
    generatedRoadmaps: "Smart Roadmaps",
    stepByStepGuide: "Step-by-Step Guide",
    teamChat: "Team Chat",
    teamChatDesc: "Quick coordination directly in the project. No external tools needed.",
    realtimeMessages: "Real-time Messages",
    mentions: "@Mentions",
    projectRelated: "Project-related",
    fileHub: "File Hub",
    fileHubDesc: "Organize and manage all your project files in one place.",
    dragDropUpload: "Drag & Drop Upload",
    folderManagement: "Folder Management",
    filePreview: "File Preview",
    canvasTitle: "Canvas",
    canvasDesc: "Brainstorming and mindmaps. Visualize your ideas together.",
    nodesConnections: "Nodes & Connections",
    colorCoding: "Color Coding",
    taskLinking: "Task Linking",
    roadmap: "Roadmap",
    ourDevelopment: "Our Development",
    whatComesNext: "What comes next",
    phase: "Phase",
    feature: "Feature",
    descriptionCol: "Description",
    status: "Status",
    betaLive: "Beta Live",
    inDevelopment: "In Development",
    planned: "Planned",
    voiceAssistant: "Voice Assistant",
    voiceAssistantDesc: "Answers questions about your project by voice",
    ideaAnalyst: "Idea Analyst",
    ideaAnalystDesc: "Validates ideas and creates roadmaps & tickets",
    businessAssistant: "Business Assistant",
    businessAssistantDesc: "Helps with business plan, structure and next steps",
    expertNetwork: "Expert Network",
    expertNetworkDesc: "Database with business analysts you can book directly",
    fairPricesForEveryTeam: "Fair prices for every team",
    choosePlanThatFits: "Choose the plan that fits you",
    basic: "Basic",
    forTheStart: "For the start",
    tba: "TBA",
    projects3: "3 Projects",
    teamMembers5: "5 Team Members",
    storage1GB: "1 GB Storage",
    basicSupport: "Basic Support",
    comingSoon: "Coming Soon",
    studentPackage: "Student Package",
    forStudentsAndUniProjects: "For Students & Uni Projects",
    unlimitedProjects: "Unlimited Projects",
    teamMembers10: "10 Team Members",
    storage10GB: "10 GB Storage",
    prioritySupport: "Priority Support",
    studentDiscount: "Student Discount",
    eduVerification: "Edu Verification",
    recommended: "Recommended",
    freshBakedStartup: "Fresh Baked Startup",
    forYoungStartups: "For Young Startups",
    everythingFromStudent: "Everything from Student Package",
    unlimitedMembers: "Unlimited Members",
    storage50GB: "50 GB Storage",
    extendedIntegrations: "Extended Integrations",
    analyticsDashboard: "Analytics Dashboard",
    readyToImplementIdea: "Ready to implement your idea?",
    startFreeNoCreditCard: "Start for free – no credit card, no commitment.",
    startFreeNow: "Start for free now",
    simplestToolForStartups: "The simplest tool for young startups.",
    hostedInGermany: "Hosted in Germany",
    
    // Startup Builder
    startupBuilderTitle: "Startup Builder",
    documentYourJourney: "Document your journey from idea to startup",
    socialFeed: "Social Feed",
    socialFeedDesc: "Share updates, ideas and progress with your team in real-time.",
    postUpdates: "Posts & Updates",
    likesComments: "Likes & Comments",
    imageSharing: "Images & GIFs",
    builder: "Builder",
    saved: "Saved",
    save: "Save",
    template: "Template",
    newRoadmap: "New Roadmap",
    progress: "Progress",
    stepsCompleted: "steps completed",
    noSavedRoadmaps: "No saved roadmaps",
    createFirstRoadmap: "Create your first startup roadmap",
    createRoadmap: "Create Roadmap",
    startYourRoadmap: "Start your roadmap",
    chooseBlockFromPalette: "Choose a block from the palette on the right or start with a template.",
    startNow: "Start now",
    saveRoadmap: "Save Roadmap",
    name: "Name",
    roadmapNamePlaceholder: "e.g. My SaaS Startup Roadmap",
    shortDescription: "Short description...",
    stepsWillBeSaved: "steps will be saved",
    cancel: "Cancel",
    archive: "Archive",
    addBlock: "Add Block",
    howWouldYouLikeToStart: "How would you like to start?",
    startWithTemplate: "Start with Template",
    templateDescription: "Use proven frameworks from well-known startup books like Lean Startup, The Mom Test or Zero to One.",
    chooseTemplate: "Choose Template",
    buildYourself: "Build Yourself",
    buildYourselfDescription: "Create your own journey from scratch. Choose from various building blocks and document each step individually.",
    flexible: "Flexible",
    dragAndDrop: "Drag & Drop",
    tenPlusBlocks: "10+ Blocks",
    letsGo: "Let's Go",
    selectTemplateFromBooks: "Select template from startup books",
    applyTemplate: "Apply Template",
    ideaValidation: "Idea Validation",
    testYourIdea: "Test your idea",
    marketResearch: "Market Research",
    analyzeMarket: "Analyze the market",
    businessModel: "Business Model",
    defineBusinessModel: "Define your business model",
    mvp: "MVP",
    buildMVP: "Build your Minimum Viable Product",
    funding: "Funding",
    secureFunding: "Secure capital",
    launch: "Launch",
    goLive: "Go live!",
    growth: "Growth",
    scaleYourBusiness: "Scale your business",
    teamBuilding: "Team",
    buildYourTeam: "Build your team",
    legal: "Legal",
    foundingAndContracts: "Founding & Contracts",
    custom: "Custom",
    ownStep: "Own step",
    planned: "Planned",
    inProgress: "In Progress",
    completed: "Completed",
    problem: "Problem",
    solution: "Solution",
    challenges: "Challenges",
    methodology: "Methodology",
    tasks: "Tasks",
    tools: "Tools",
    keyLearnings: "Key Learnings",
    editStep: "Edit",
    deleteStep: "Delete",
    deleteStepConfirm: "Do you really want to delete this step?",
    by: "by",
    
    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    close: "Close",
    edit: "Edit",
    view: "View",
    create: "Create",
    update: "Update",
    remove: "Remove",
    add: "Add",
    yes: "Yes",
    no: "No",
  },
  de: {
    // German removed – app is English only for Hostinger
    allProjects: "All Projects",
    settings: "Einstellungen",
    logout: "Abmelden",
    online: "Online",
    search: "Suchen...",
    calendar: "Kalender",
    noTasksInColumn: "Keine Tickets in dieser Spalte.",
    dragHint: "überall ziehbar",
    validation: "Validierung",
    startupBuilder: "Startup Builder",
    integrations: "Integrationen",
    notifications: "Benachrichtigungen",
    noNotifications: "Keine neuen Benachrichtigungen",
    newPosts: "neue Beiträge",
    newMessages: "neue Nachrichten",
    liveNotifyTitle: "Team-Aktivität",
    liveNotifyFeed:
      "Der Feed wurde aktualisiert (Beitrag, Reaktion oder Kommentar).",
    liveNotifyComment: "Jemand hat den Feed kommentiert.",
    liveNotifyChat: "Neue Chat-Nachricht.",
    liveNotifyBoard:
      "Aufgaben, Unteraufgaben oder Ticket-Kommentare wurden geändert.",
    liveNotifyDocs: "Notizen wurden aktualisiert.",
    liveNotifyFiles: "Dateien oder Ordner wurden geändert.",
    liveNotifyCanvas: "Das Canvas wurde aktualisiert.",
    liveNotifyTools: "Integrationen wurden geändert.",
    liveNotifyCalendar: "Der Kalender wurde aktualisiert.",
    liveNotifyStartup: "Startup Builder wurde aktualisiert.",
    liveNotifyValidation: "Produktideen wurden aktualisiert.",
    liveNotifyGeneric: "Das Projekt wurde aktualisiert.",
    notificationFeedUnread: "{{count}} neue Beiträge im Feed",
    notificationChatUnread: "{{count}} neue Chat-Nachrichten",
    notificationTeamHeading: "Team-Aktivität",
    notificationClearTeam: "Team-Meldungen leeren",
    editProfile: "Profil bearbeiten",
    subscription: "Abonnement",
    language: "Sprache",
    english: "Englisch",
    german: "Deutsch",
    
    // Navigation
    dashboard: "Dashboard",
    overview: "Feeds",
    tasks: "Kanban Board",
    docs: "Notizen",
    canvas: "Canvas",
    files: "Dateien",
    chat: "Chat",

    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Die wichtigsten Kennzahlen und offene Arbeit auf einen Blick.",
    dashboardTasksDone: "Abgeschlossene Tickets",
    dashboardTasksOpen: "Offene Tickets",
    dashboardTasksInProgress: "In Bearbeitung",
    dashboardAssignedToMe: "Mir zugewiesen",
    dashboardTicketOverview: "Ticket-Übersicht",
    dashboardCompletion: "Fortschritt",
    dashboardCompletionDetail: "{{done}} von {{total}} Tickets erledigt",
    dashboardStatusTodo: "To Do",
    dashboardStatusProgress: "In Arbeit",
    dashboardStatusReview: "Review",
    dashboardStatusDone: "Erledigt",
    dashboardSubtasks: "{{done}} Subtasks erledigt · {{open}} offen",
    dashboardHighPriority: "{{count}} Tickets mit hoher Priorität noch offen",
    dashboardModules: "Module",
    dashboardGoToBoard: "Zum Kanban",
    dashboardOpenTickets: "Offene Tickets",
    dashboardViewAll: "Alle anzeigen",
    dashboardNoOpenTasks: "Keine offenen Tickets — stark!",
    dashboardRecentlyDone: "Zuletzt abgeschlossen",
    dashboardNoDoneYet: "Noch keine erledigten Tickets.",
    dashboardUntitled: "Ohne Titel",
    dashboardUpcomingEvents: "Kommende Termine",

    // Common UI
    filesTitle: "Dateien",
    filesSubtitle: "Dateien und Dokumente verwalten",
    uploadFiles: "Dateien hochladen",
    uploadingCount: "Hochladen… ({{count}})",
    dropFilesHere: "Dateien hier ablegen",
    tapToUpload: "Tippen zum Hochladen",
    newFolder: "Neuer Ordner",
    folderName: "Ordnername",
    createFolder: "Ordner erstellen",
    deleteAllFiles: "Alle Dateien löschen?",
    backToOverview: "Zurück zur Übersicht",
    previewUnavailable: "Vorschau nicht verfügbar",
    downloadFile: "Herunterladen",
    fileMissing: "Datei fehlt",
    shareLink: "Link teilen",
    copied: "Kopiert",
    fullscreen: "Vollbild",
    loadingShort: "Laden…",
    projectFeed: "Projekt Feed",
    feedSubtitle: "Neuigkeiten, Ankündigungen und Team-Diskussionen.",
    feedLoading: "Feed wird geladen…",
    feedLoadFailed: "Feed konnte nicht geladen werden",
    retry: "Erneut laden",
    whatsNew: "Was gibt's Neues?",
    photosCount: "Fotos ({{used}}/{{max}})",
    uploading: "Wird hochgeladen…",
    postSubmit: "Beitrag posten",
    posting: "Wird gepostet…",
    postFailed: "Beitrag konnte nicht gespeichert werden.",
    noPostsYet: "Noch keine Beiträge",
    createFirstPost: "Schreib den ersten!",
    teamMember: "Teammitglied",
    react: "Reagieren",
    commentsCount: "{{count}} Kommentare",
    writeComment: "Kommentar schreiben…",
    noCommentsYet: "Noch keine Kommentare",
    delete: "Löschen",
    pinPost: "Beitrag anpinnen",
    unpinPost: "Beitrag loesen",
    pinnedPost: "Angepinnt",
    pinFailed: "Anpinnen konnte nicht gespeichert werden.",
    noProjectAccess: "Kein Zugriff auf dieses Projekt",
    backToProjects: "Zurueck zu Projekten",
    tryAgain: "Erneut versuchen",
    
    // ProjectsList
    myProjects: "Meine Projekte",
    selectProject: "Wählen Sie ein Projekt aus oder erstellen Sie ein neues",
    createProject: "Projekt erstellen",
    newProject: "Neues Projekt",
    projectName: "Projektname",
    projectNamePlaceholder: "z.B. Mein Projekt",
    description: "Beschreibung (optional)",
    descriptionPlaceholder: "Worum geht es in diesem Projekt...",
    createAndOpen: "Erstellen und Öffnen",
    noProjects: "Keine Projekte",
    noProjectsDesc: "Erstellen Sie Ihr erstes Projekt, um zu beginnen",
    createFirstProject: "Erstes Projekt erstellen",
    noDescription: "Keine Beschreibung",
    members: "Mitglieder",
    deleteProject: "Projekt löschen",
    deleteProjectConfirm: "Projekt wirklich löschen?",

    // ProjectsList (extended)
    ideaHubTitle: "Ideen Hub",
    ideaHubSubtitle: "Ideen sammeln — bei Bedarf als Projekt starten.",
    ideaHubAdd: "Neue Idee",
    ideaHubAddFirst: "Erste Idee anlegen",
    ideaHubBack: "Zurück zu Projekten",
    ideaHubEmptyTitle: "Noch keine Ideen",
    ideaHubEmptyDesc: "Halte Produktideen, Features oder Nebenprojekte fest. Mit einem Klick wird daraus ein volles Projekt.",
    ideaHubOpenSection: "Offene Ideen",
    ideaHubConvertedSection: "Als Projekt gestartet",
    ideaHubFieldTitle: "Titel",
    ideaHubFieldTitlePlaceholder: "z. B. Moodtracker für Teams",
    ideaHubFieldDesc: "Notizen (optional)",
    ideaHubFieldDescPlaceholder: "Welches Problem löst es? Für wen?",
    ideaHubEdit: "Idee bearbeiten",
    ideaHubStartProject: "Als Projekt starten",
    ideaHubOpenProject: "Projekt öffnen",
    ideaHubStatusOpen: "Offen",
    ideaHubStatusConverted: "Projekt",
    ideaHubNoDescription: "Keine Notizen",
    ideaHubTitleRequired: "Bitte einen Titel eingeben.",
    ideaHubSaveFailed: "Idee konnte nicht gespeichert werden",
    ideaHubDeleteFailed: "Idee konnte nicht gelöscht werden",
    ideaHubConvertFailed: "Projekt konnte nicht erstellt werden",
    ideaHubProjectCreated: "Projekt erstellt",
    ideaHubLoading: "Ideen werden geladen…",
    ideaHubLocalOnlyHint: "Ideen liegen nur in diesem Browser. Mit Google anmelden für Sync auf allen Geräten.",
    decideWhatToDo: "Was möchtest du tun?",
    chooseOptionToStart: "Wähle eine Option um zu starten",
    toMyProjects: "Zu meinen Projekten",
    newShort: "Neu",
    projectCreateFailedTitle: "Projekt konnte nicht erstellt werden",
    projectCreateFailedDesc: "Bitte mit Google anmelden für Cloud-Speicher oder Fehler prüfen.",
    enterProjectName: "Bitte Projektname eingeben",
    retry: "Erneut versuchen",
    createFirstProjectCta: "Erstes Projekt erstellen",
    hiddenAllTitle: "Alle Projekte sind ausgeblendet",
    hiddenAllDesc: "Blende Projekte wieder ein oder erstelle ein neues.",
    showHidden: "Ausgeblendete anzeigen",
    editProject: "Projekt bearbeiten",
    name: "Name",
    coverImage: "Cover Image",
    membersMax: "Members (max {{max}})",
    commaSeparated: "Kommagetrennt.",
    save: "Speichern",
    saving: "Speichert…",
    viewToggleList: "List",
    viewToggleGrid: "Grid",
    reset: "Reset",
    statsLoading: "Stats…",
    workspace: "Workspace",
    dragProjectsHere: "Drag projects here",
    dropProjectsHere: "Drop projects here to pin them to your workspace.",
    favorites: "Favorites",
    projects: "Projekte",
    projectsMine: "Meine Projekte",
    projectsSharedWithMe: "Mit mir geteilt",
    projectsSharedHint:
      "Du bist als Mitglied eingeladen. Projekteinstellungen bearbeiten nur der/die Ersteller:in.",
    noOwnProjectsYet: "Du hast noch keine eigenen Projekte — leg oben mit „Neu“ eines an.",
    totalTime: "Zeit gesamt",
    last: "Zuletzt",
    notTrackedYet: "Noch nie getrackt",
    feeds: "Feeds",
    activeModules: "Aktive Module",
    removeFromWorkspace: "Remove from workspace",
    timerSyncedHint:
      "Die erfasste Zeit wird gespeichert, wenn du den Timer stoppst oder den Tab verlässt. Auf dem anderen Gerät Projektliste öffnen und aktualisieren – dieselben Minuten erscheinen (Anmeldung mit Google nötig).",
    projectDoneBadge: "Erledigt",
    markProjectDone: "Projekt als erledigt markieren",
    markProjectActive: "Projekt wieder aktiv",
    projectMarkDoneLabel: "Projekt abgeschlossen",
    projectMarkDoneHint: "Erledigte Projekte bleiben sichtbar; du kannst sie jederzeit wieder öffnen.",
    
    // Tasks
    sprintBoard: "Sprint Board",
    addTask: "Aufgabe hinzufügen",
    clearAll: "Alles löschen",
    createNewTask: "Neue Aufgabe erstellen",
    editTask: "Aufgabe bearbeiten",
    taskTitle: "Aufgabentitel",
    priority: "Priorität",
    dependencies: "Abhängigkeiten",
    mentionAll: "Alle",
    calendarLoading: "Termine werden geladen…",
    contactCareTitle: "Kontaktpflege",
    contactCareSettingDesc: "Lass dich erinnern, drei Menschen anzuschreiben — um Beziehungen zu pflegen und neue zu knüpfen. Das ist persönlich und gilt für alle deine Projekte.",
    contactCareEnable: "Erinnere mich",
    contactCareInterval: "Wie oft?",
    contactCareEvery: "Alle {n} Tag(e)",
    contactCarePrompt: "Schreib heute drei Menschen. Wem hast du geschrieben?",
    contactCareName: "Name",
    contactCareHint: "Die Karte blinkt, bis alle drei Namen drinstehen.",
    contactCareReady: "Sehr gut — speichern, dann ist Ruhe.",
    contactCareDone: "Erledigt, drei Kontakte",
    contactCareThanks: "Gespeichert. Gut gemacht.",
    contactCareAllGood: "Alles gepflegt.",
    contactCareNext: "Nächste Erinnerung: {date}.",
    contactCareLast: "Zuletzt",
    newEvent: "Termin",
    eventTitle: "Titel",
    eventDescription: "Beschreibung (optional)",
    eventStart: "Start",
    eventEnd: "Ende",
    eventColor: "Farbe",
    joinVideoInApp: "Videokonferenz in ORBYLOX beitreten",
    noEventsThisMonth: "Keine Termine in diesem Monat.",
    tapDayToAdd: "Tippe auf einen Tag, um einen anzulegen.",
    allDay: "Ganztägig",
    chatPlaceholder: "Nachricht… (@ für Erwähnung)",
    mentionedYou: "hat dich erwähnt",
    openChat: "Chat öffnen",
    waitsFor: "Wartet auf",
    blocksTheseTasks: "Blockiert diese Tickets",
    addDependency: "Ticket hinzufügen, auf das gewartet wird",
    searchTicket: "Ticket suchen…",
    noDependencies: "Wartet auf nichts — kann sofort bearbeitet werden.",
    blockedBadge: "Blockiert",
    blockedByCount: "Blockiert von {n} offenen Ticket(s)",
    cannotMoveToDone: "Dieses Ticket wartet noch auf: {list}",
    removeDependency: "Abhängigkeit entfernen",
    noTicketsFound: "Kein passendes Ticket",
    wouldLoop: "Geht nicht — das ergäbe einen Kreis.",
    assignedMailSent: "{name} wurde per E-Mail informiert.",
    assignTo: "Zuweisen an...",
    unassigned: "Nicht zugewiesen",
    available: "Verfügbar",
    person: "Person",
    people: "Personen",
    goToSettings: "Gehen Sie zu Einstellungen, um Team hinzuzufügen",
    updateTask: "Aufgabe aktualisieren",
    createTask: "Aufgabe erstellen",
    deleteAllTasks: "Alle Aufgaben löschen?",
    low: "Niedrig",
    medium: "Mittel",
    high: "Hoch",
    todo: "Zu erledigen",
    inProgress: "In Bearbeitung",
    review: "Überprüfung",
    done: "Fertig",
    
    // Settings
    projectSettings: "Projekteinstellungen",
    managePreferences: "Verwalten Sie Ihre Projekteinstellungen und Ihr Team.",
    generalInfo: "Allgemeine Informationen",
    updateDetails: "Aktualisieren Sie Ihre Projektdetails.",
    teamMembers: "Teammitglieder",
    inviteFriends: "Laden Sie Freunde zur Zusammenarbeit am Projekt ein. Sie erhalten eine E-Mail-Einladung.",
    inviteToProject: "Zum Projekt einladen",
    howToInvite: "Wie lade ich Freunde ein?",
    inviteStep1: "1. Klicken Sie oben auf 'Zum Projekt einladen'",
    inviteStep2: "2. Geben Sie die E-Mail Ihres Freundes ein",
    inviteStep3: "3. Wir senden automatisch eine Einladung",
    inviteStep4: "4. Nach dem Einloggen sehen sie alle Änderungen in Echtzeit!",
    features: "Funktionen",
    enableDisableFeatures: "Aktiviere oder deaktiviere Features.",
    textToTicket: "Text zu Ticket",
    textToTicketDesc: "Markiere Text um automatisch Tickets zu erstellen",
    backupRestore: "Backup & Wiederherstellung",
    createBackups: "Erstelle Backups und stelle dein Projekt wieder her.",
    
    // Canvas
    clearAllItems: "Alle Elemente löschen?",
    typeHere: "Hier tippen...",
    writeHere: "Hier schreiben...",
    
    // Chat
    teamChat: "Team Chat",
    typeMessage: "Nachricht eingeben...",
    send: "Senden",
    deleteAllMessages: "Alle Nachrichten löschen?",
    team: "Team",
    deleteChatHistory: "Chat-Verlauf löschen?",
    startVideoCall: "Video Call starten",
    
    // Docs
    documents: "Dokumente",
    newDocument: "Neues Dokument",
    deleteAllDocs: "Alle Dokumente löschen?",
    untitledDocument: "Unbenanntes Dokument",
    noDocSelected: "Kein Dokument ausgewählt",
    selectOrCreate: "Wählen Sie ein Dokument aus der Liste oder erstellen Sie ein neues",
    dragDropFiles: "Dateien hier ablegen",
    orClick: "oder klicken zum Durchsuchen",
    uploadedFiles: "Hochgeladene Dateien",
    
    // FileHub
    myFiles: "Meine Dateien",
    uploadFile: "Datei hochladen",
    deleteAllFiles: "Alle Dateien löschen?",
    folders: "Ordner",
    recentFiles: "Kürzliche Dateien",
    download: "Herunterladen",
    delete: "Löschen",
    
    // Landing
    forStudentsAndStartups: "Für Studierende & junge Startups",
    planProjects: "Projekte planen.",
    implementIdeas: "Ideen umsetzen.",
    landingSubtitle: "ORBYLOX ist euer All-in-One Projektmanagement-Tool mit integrierter Ideen-Validierung. Perfekt für Teams, die strukturiert arbeiten und ihre Visionen verwirklichen wollen.",
    readyIn10Min: "In 5 Min. startklar",
    gdprCompliant: "DSGVO-konform",
    studentFriendly: "Studentenfreundlich",
    startFree: "Kostenlos starten",
    login: "Anmelden",
    builtForTeamsLikeYou: "Gebaut für Teams wie euch",
    students: "Studierende",
    studentsDesc: "Die ihr erstes Projekt oder Startup starten wollen",
    freshStartups: "Frische Startups",
    freshStartupsDesc: "Teams von 1–5 Personen mit großen Ideen",
    friendGroups: "Freundesgruppen",
    friendGroupsDesc: "Die gemeinsam ein Startup gründen wollen",
    whatMakesSpecial: "Was ORBYLOX besonders macht",
    simpleStartGrowTogether: "Einfach starten, gemeinsam wachsen.",
    min10Onboarding: "5 Minuten Onboarding",
    min10OnboardingDesc: "Kein Funktions-Overload. Starte sofort ohne komplizierte Einrichtung.",
    minimalistInterface: "Minimalistisches Interface",
    minimalistInterfaceDesc: "Klarer Fokus auf das Wesentliche. Einfach zu verstehen, einfach zu nutzen.",
    fromIdeaToPlan: "Von der Idee zum Plan",
    fromIdeaToPlanDesc: "Für Einsteiger gebaut: Validiere deine Idee und erstelle konkrete erste Schritte.",
    gdprCompliantTitle: "DSGVO-konform",
    gdprCompliantDesc: "Deine Daten bleiben in Deutschland. Datenschutz ist bei uns kein Kompromiss.",
    studentFriendlyTitle: "Studentenfreundlich",
    studentFriendlyDescLong: "Faire Preise für Teams, die gerade erst starten. Kein Enterprise-Pricing.",
    ideaValidationIntegrated: "Ideen-Validierung integriert",
    ideaValidationIntegratedDesc: "Prüfe deine Business-Idee mit Methoden aus Lean Startup, Design Thinking & mehr.",
    everythingYouNeed: "Alles was ihr braucht",
    focusedToolsNoOverload: "Fokussierte Tools ohne Überladung",
    kanbanBoard: "Kanban Board",
    kanbanBoardDesc: "Organisiert eure Aufgaben visuell. Drag & Drop, Prioritäten, Zuweisung – alles dabei.",
    dragDropInterface: "Drag & Drop Interface",
    prioritiesDeadlines: "Prioritäten & Deadlines",
    teamAssignment: "Team-Zuweisung",
    ideaValidation: "Ideen-Validierung",
    ideaValidationDesc: "Prüft eure Business-Idee mit bewährten Methoden wie Lean Startup oder Design Thinking.",
    validationMethods: "5 Validierungs-Methoden",
    generatedRoadmaps: "Smart Roadmaps",
    stepByStepGuide: "Schritt-für-Schritt Anleitung",
    teamChat: "Team Chat",
    teamChatDesc: "Schnelle Abstimmungen direkt im Projekt. Keine externen Tools nötig.",
    realtimeMessages: "Echtzeit-Nachrichten",
    mentions: "@Mentions",
    projectRelated: "Projekt-bezogen",
    fileHub: "Datei-Hub",
    fileHubDesc: "Organisiere und verwalte alle Projekt-Dateien an einem Ort.",
    dragDropUpload: "Drag & Drop Upload",
    folderManagement: "Ordner-Verwaltung",
    filePreview: "Dateivorschau",
    canvasTitle: "Canvas",
    canvasDesc: "Brainstorming und Mindmaps. Visualisiert eure Ideen gemeinsam.",
    nodesConnections: "Nodes & Verbindungen",
    colorCoding: "Farbcodierung",
    taskLinking: "Task-Verknüpfung",
    roadmap: "Roadmap",
    ourDevelopment: "Unsere Entwicklung",
    whatComesNext: "Was kommt als nächstes",
    phase: "Phase",
    feature: "Feature",
    descriptionCol: "Beschreibung",
    status: "Status",
    betaLive: "Beta Live",
    inDevelopment: "In Entwicklung",
    planned: "Geplant",
    voiceAssistant: "Voice Assistant",
    voiceAssistantDesc: "Answers questions about your project by voice",
    ideaAnalyst: "Idea Analyst",
    ideaAnalystDesc: "Validates ideas and creates roadmaps & tickets",
    businessAssistant: "Business Assistant",
    businessAssistantDesc: "Helps with business plan, structure and next steps",
    expertNetwork: "Experten-Netzwerk",
    expertNetworkDesc: "Datenbank mit Business-Analysten, die ihr direkt buchen könnt",
    fairPricesForEveryTeam: "Faire Preise für jedes Team",
    choosePlanThatFits: "Wählt den Plan, der zu euch passt",
    basic: "Basic",
    forTheStart: "Für den Einstieg",
    tba: "TBA",
    projects3: "3 Projekte",
    teamMembers5: "5 Team-Mitglieder",
    storage1GB: "1 GB Speicher",
    basicSupport: "Basis-Support",
    comingSoon: "Coming Soon",
    studentPackage: "Studentenpaket",
    forStudentsAndUniProjects: "Für Studierende & Uni-Projekte",
    unlimitedProjects: "Unbegrenzte Projekte",
    teamMembers10: "10 Team-Mitglieder",
    storage10GB: "10 GB Speicher",
    prioritySupport: "Priority Support",
    studentDiscount: "Studentenrabatt",
    eduVerification: "Edu-Verifizierung",
    recommended: "Empfohlen",
    freshBakedStartup: "Fresh Baked Startup",
    forYoungStartups: "Für junge Startups",
    everythingFromStudent: "Alles aus Studentenpaket",
    unlimitedMembers: "Unbegrenzte Mitglieder",
    storage50GB: "50 GB Speicher",
    extendedIntegrations: "Erweiterte Integrationen",
    analyticsDashboard: "Analytics Dashboard",
    readyToImplementIdea: "Bereit, eure Idee umzusetzen?",
    startFreeNoCreditCard: "Startet kostenlos – ohne Kreditkarte, ohne Verpflichtung.",
    startFreeNow: "Jetzt kostenlos starten",
    simplestToolForStartups: "Das einfachste Tool für junge Startups.",
    hostedInGermany: "Gehostet in Deutschland",
    
    // Startup Builder
    startupBuilderTitle: "Startup Builder",
    documentYourJourney: "Dokumentiere deinen Weg vom Idea zum Startup",
    socialFeed: "Social Feed",
    socialFeedDesc: "Teile Updates, Ideen und Fortschritte mit deinem Team in Echtzeit.",
    postUpdates: "Posts & Updates",
    likesComments: "Likes & Kommentare",
    imageSharing: "Bilder & GIFs",
    builder: "Builder",
    saved: "Gespeichert",
    save: "Speichern",
    template: "Vorlage",
    newRoadmap: "Neue Roadmap",
    progress: "Fortschritt",
    stepsCompleted: "Schritte abgeschlossen",
    noSavedRoadmaps: "Keine Roadmaps gespeichert",
    createFirstRoadmap: "Erstelle deine erste Startup-Roadmap",
    createRoadmap: "Roadmap erstellen",
    startYourRoadmap: "Starte deine Roadmap",
    chooseBlockFromPalette: "Wähle einen Baustein aus der Palette rechts oder starte mit einer Vorlage.",
    startNow: "Jetzt starten",
    saveRoadmap: "Roadmap speichern",
    name: "Name",
    roadmapNamePlaceholder: "z.B. Meine SaaS Startup Roadmap",
    shortDescription: "Kurze Beschreibung...",
    stepsWillBeSaved: "Schritte werden gespeichert",
    cancel: "Abbrechen",
    archive: "Archivieren",
    addBlock: "Baustein hinzufügen",
    howWouldYouLikeToStart: "Wie möchtest du starten?",
    startWithTemplate: "Mit Vorlage starten",
    templateDescription: "Nutze bewährte Frameworks aus bekannten Startup-Büchern wie Lean Startup, The Mom Test oder Zero to One.",
    chooseTemplate: "Vorlage wählen",
    buildYourself: "Selbst bauen",
    buildYourselfDescription: "Erstelle deine eigene Journey von Grund auf. Wähle aus verschiedenen Bausteinen und dokumentiere jeden Schritt individuell.",
    flexible: "Flexibel",
    dragAndDrop: "Drag & Drop",
    tenPlusBlocks: "10+ Bausteine",
    letsGo: "Los geht's",
    selectTemplateFromBooks: "Vorlage aus Startup-Büchern wählen",
    applyTemplate: "Vorlage anwenden",
    ideaValidation: "Ideen-Validierung",
    testYourIdea: "Teste deine Idee",
    marketResearch: "Marktforschung",
    analyzeMarket: "Analysiere den Markt",
    businessModel: "Business Model",
    defineBusinessModel: "Definiere dein Geschäftsmodell",
    mvp: "MVP",
    buildMVP: "Baue dein Minimum Viable Product",
    funding: "Finanzierung",
    secureFunding: "Sichere dir Kapital",
    launch: "Launch",
    goLive: "Gehe live!",
    growth: "Wachstum",
    scaleYourBusiness: "Skaliere dein Business",
    teamBuilding: "Team",
    buildYourTeam: "Baue dein Team auf",
    legal: "Rechtliches",
    foundingAndContracts: "Gründung & Verträge",
    custom: "Custom",
    ownStep: "Eigener Schritt",
    planned: "Geplant",
    inProgress: "In Arbeit",
    completed: "Abgeschlossen",
    problem: "Problem",
    solution: "Lösung",
    challenges: "Herausforderungen",
    methodology: "Methodik",
    tasks: "Aufgaben",
    tools: "Tools",
    keyLearnings: "Key Learnings",
    editStep: "Bearbeiten",
    deleteStep: "Löschen",
    deleteStepConfirm: "Möchtest du diesen Schritt wirklich löschen?",
    by: "von",
    
    // Common
    loading: "Laden...",
    error: "Fehler",
    success: "Erfolg",
    confirm: "Bestätigen",
    close: "Schließen",
    edit: "Bearbeiten",
    view: "Ansehen",
    create: "Erstellen",
    update: "Aktualisieren",
    remove: "Entfernen",
    add: "Hinzufügen",
    yes: "Ja",
    no: "Nein",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = (localStorage.getItem('orbylox_language') || '').toLowerCase();
      if (saved === 'de' || saved === 'en') return saved;
    } catch {
      // ignore
    }
    return 'en';
  });

  /** Zielsprache, solange die grüßende Figur läuft; sonst null. */
  const [salutingTo, setSalutingTo] = useState(null);

  useEffect(() => {
    // Ohne try/catch reisst ein blockierter Speicher die ganze Anwendung mit:
    // im privaten Modus mancher Browser wirft setItem. Das Lesen war bereits
    // abgesichert, das Schreiben nicht.
    try {
      localStorage.setItem('orbylox_language', language);
    } catch {
      // Dann gilt die Sprache eben nur für diese Sitzung.
    }
  }, [language]);

  /**
   * Sprachwechsel mit Gruß.
   *
   * Die Figur grüßt, und in dem Moment, in dem die Hand oben steht, springt
   * die Sprache um. Wer weniger Bewegung eingestellt hat, bekommt den Wechsel
   * sofort — eine Systemeinstellung wiegt schwerer als eine Verzierung.
   *
   * Ein zweiter Klick während des Grußes heißt "jetzt aber": die Bewegung
   * wird übersprungen, umgeschaltet wird sofort. Umgeschaltet wird dabei auf
   * die bereits angestoßene Zielsprache — die neu berechnete wäre falsch,
   * denn `language` steht noch auf dem alten Wert.
   */
  const requestLanguageChange = (next) => {
    if (salutingTo) {
      setLanguage(salutingTo);
      setSalutingTo(null);
      return;
    }

    const target = next === 'en' ? 'en' : 'de';
    if (target === language) return;

    const reduceMotion =
      typeof window !== 'undefined' &&
      window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

    if (reduceMotion) {
      setLanguage(target);
      return;
    }
    setSalutingTo(target);
  };

  /**
   * Three.js, Modell und Bewegung schon beim Berühren des Knopfes holen.
   * Ohne das würde der erste Klick auf den Download warten — und genau dann
   * greift die Reißleine und der Gruß fällt aus.
   */
  const prefetchSalute = () => {
    import('@/components/bot/ClipBot')
      .then((m) => m.prefetchClip?.('/models/salute.clip.json'))
      .catch(() => {});
  };

  const t = (key, vars = null) => {
    const template = translations?.[language]?.[key] || translations?.en?.[key] || key;
    if (!vars) return template;
    return Object.entries(vars).reduce(
      (acc, [k, v]) => acc.replaceAll(`{{${k}}}`, String(v)),
      template
    );
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, requestLanguageChange, prefetchSalute, t }}
    >
      {children}
      {salutingTo && (
        <LanguageSalute
          to={salutingTo}
          onApply={() => setLanguage(salutingTo)}
          onClose={() => setSalutingTo(null)}
        />
      )}
      {/* Hört auf celebrate() — der Jubel, wenn ein Ticket fertig wird.
          Steht hier, weil dieser Anbieter auf jeder Seite liegt. */}
      <CelebrationHost language={language} />
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}